// =============================================================================
// cpu.cpp — CPU clock PIO initialisation
//
// Loads cpu_clock.pio into PIO0 SM3 and configures the CLOCK output pin
// (GP25). The SM runs at 7 MHz (PIO0_CLK_DIV = 36) in lockstep with the
// sync and pixel SMs so the CPU clock is phase-coherent with the video output.
//
// Core 0's raster loop feeds one contention bit per half pixel-clock into
// the SM3 TX FIFO:
//   0 → clock free to toggle (normal 3.5 MHz operation)
//   1 → hold clock HIGH (CPU stalled — ULA owns the bus)
//
// The SM drives the CLOCK pin via side-set, so the output transitions are
// glitch-free and cycle-accurate regardless of when the FIFO word arrives.
// =============================================================================

#include "cpu.h"
#include "pinmap.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "pico/stdlib.h"

#include "cpu_clock.pio.h"  // generated by pioasm via CMakeLists

#define SM_CPUCLK   3       // PIO0 SM3

void cpu_init(void) {
    // Load cpu_clock program into PIO0
    uint offset = pio_add_program(pio0, &cpu_clock_program);

    pio_sm_config c = cpu_clock_program_get_default_config(offset);

    // Side-set pin: CLOCK output (GP25)
    sm_config_set_sideset_pins(&c, PIN_CLOCK);

    // Clock divider: 252 MHz / 36 = 7 MHz — matches sync and pixel SMs
    sm_config_set_clkdiv_int_frac(&c, PIO0_CLK_DIV, 0);

    // Autopull: pull one bit at a time from TX FIFO (contention flag)
    // Shift right, threshold=1, autopull enabled
    sm_config_set_out_shift(&c, true, true, 1);

    // FIFO: TX only (SM reads contention bits, no RX needed)
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);

    pio_sm_init(pio0, SM_CPUCLK, offset, &c);

    // Configure CLOCK pin as PIO output
    pio_gpio_init(pio0, PIN_CLOCK);
    pio_sm_set_consecutive_pindirs(pio0, SM_CPUCLK, PIN_CLOCK, 1, true);

    // Pre-fill FIFO with "no contention" so clock starts toggling immediately
    // when the SM is enabled (it won't stall on an empty FIFO at first tick)
    for (int i = 0; i < 4; i++)
        pio_sm_put(pio0, SM_CPUCLK, 0u);

    // NOTE: SM3 is started by video_init() together with SM0/SM1/SM2 using
    // pio_enable_sm_mask_in_sync() so all four SMs begin on the same cycle.
    // Do NOT call pio_sm_set_enabled() here — leave that to video_init().
}
